### ISSUE TITLE
sendcommandfeedback does not work

### ISSUE THREAD

**Issue by WillXProject** [NightwalkerLots/UAC-Public#24]
Please add a toggle for this

**Comment by NightwalkerLots** [comment]
not a bug. done on purpose

**Comment by WillXProject** [comment]
I said, "Please add a toggle for this"

**Comment by NightwalkerLots** [comment]
No. Like I said it is like that for a reason. UAC has a number of commands running at a given time. Having feedback on would clog chat for everyone. Please use the discord server to relay further feedback.
